from __future__ import annotations

import json
import os
import re
import sqlite3
import time
import zlib
from threading import Lock
from pathlib import Path
from typing import Any

import requests
from flask import Flask, abort, current_app, g, jsonify, redirect, render_template, request, url_for

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - dependency is optional for deployment environments
    load_dotenv = None


BASE_DIR = Path(__file__).resolve().parent
if load_dotenv:
    load_dotenv(BASE_DIR / ".env")

DEFAULT_DATABASE = BASE_DIR / "symptom_triage.db"
DEFAULT_APIFREE_BASE_URL = "https://api.apifree.ai/v1"
DEFAULT_APIFREE_MODEL = "deepseek-ai/deepseek-v4-flash"
APIFREE_REQUEST_LOCK = Lock()


class LiveAIRequiredError(RuntimeError):
    """Raised when an AI-labelled feature cannot get a live APIFree result."""

DISCLAIMER_TEXT = (
    "This website is not a diagnosis tool, does not replace a doctor, and does not provide prescriptions. "
    "If symptoms are severe, rapidly worsening, or concerning, seek urgent professional medical help."
)
BRIEF_DISCLAIMER_TEXT = "Info only. Not diagnosis or prescription. Seek urgent care for severe or worsening symptoms."
MEDICATION_BOUNDARY_TEXT = (
    "Medication items are AI-generated discussion references only. This app does not recommend personal doses, "
    "does not prescribe medicine, and does not replace a doctor or pharmacist."
)
DOSE_BOUNDARY_TEXT = "Dose not generated by this app. Follow the medicine label or a licensed clinician/pharmacist."
UNSAFE_DOSAGE_PATTERN = re.compile(
    r"(\b\d+(\.\d+)?\s?(mg|mcg|g|ml|mL|iu|units?|tablets?|capsules?|pills?)\b)|"
    r"(\b(take|use)\s+\d+\b)|"
    r"(\b\d+\s?(x|times?)\s?(a|per)?\s?(day|daily|hour|hours?)\b)",
    re.IGNORECASE,
)

RED_FLAG_RULES = [
    ("chest_pain", r"\b(chest pain|chest pressure|tight chest|胸痛|胸闷)\b"),
    ("breathing", r"\b(difficulty breathing|trouble breathing|shortness of breath|cannot breathe|breathless|呼吸困难|喘不过气)\b"),
    ("stroke_signs", r"\b(one side weak|facial droop|slurred speech|sudden weakness|sudden numbness|单侧无力|口齿不清)\b"),
    ("confusion", r"\b(confusion|unable to wake|fainting|loss of consciousness|意识混乱|昏厥|无法唤醒)\b"),
    ("severe_bleeding", r"\b(severe bleeding|uncontrolled bleeding|大量出血|止不住血)\b"),
    ("self_harm", r"\b(self harm|suicide|kill myself|自残|自杀)\b"),
    ("blue_lips", r"\b(blue lips|blue skin|pale gray skin|嘴唇发青|皮肤发青)\b"),
    ("severe_abdominal", r"\b(severe abdominal pain|severe stomach pain|剧烈腹痛)\b"),
]


def resolve_ai_settings() -> dict[str, Any]:
    apifree_key = (os.environ.get("APIFREE_API_KEY") or os.environ.get("API_KEY") or "").strip()
    return {
        "AI_API_KEY": apifree_key or None,
        "AI_PROVIDER": "APIFree",
        "AI_BASE_URL": os.environ.get("APIFREE_BASE_URL") or DEFAULT_APIFREE_BASE_URL,
        "AI_MODEL": os.environ.get("APIFREE_MODEL") or DEFAULT_APIFREE_MODEL,
    }


def create_app(test_config: dict[str, Any] | None = None) -> Flask:
    app = Flask(__name__, instance_relative_config=True)
    ai_settings = resolve_ai_settings()
    app.config.from_mapping(
        DATABASE=os.environ.get("DATABASE_PATH", str(DEFAULT_DATABASE)),
        SECRET_KEY=os.environ.get("SECRET_KEY", "dev-only-change-me"),
        **ai_settings,
        AI_TIMEOUT_SECONDS=30,
        AI_LAST_ERROR=None,
    )

    if test_config:
        app.config.update(test_config)

    register_database_hooks(app)
    register_routes(app)
    ensure_runtime_schema(app)

    @app.context_processor
    def inject_ai_status() -> dict[str, Any]:
        return {
            "ai_configured": bool(app.config.get("AI_API_KEY")),
            "ai_provider_name": app.config.get("AI_PROVIDER") or "APIFree",
            "ai_model_name": app.config.get("AI_MODEL") or "not configured",
            "ai_base_url": app.config.get("AI_BASE_URL") or "not configured",
            "ai_last_error": app.config.get("AI_LAST_ERROR"),
        }

    return app


def get_db() -> sqlite3.Connection:
    if "db" not in g:
        database = current_app.config["DATABASE"]
        connection = sqlite3.connect(database)
        connection.row_factory = sqlite3.Row
        g.db = connection
    return g.db


def register_database_hooks(app: Flask) -> None:
    @app.teardown_appcontext
    def close_db(error: BaseException | None = None) -> None:
        connection = g.pop("db", None)
        if connection is not None:
            connection.close()

    @app.cli.command("init-db")
    def init_db_command() -> None:
        init_db(app)
        print("Initialized the symptom intake database.")


def init_db(app: Flask) -> None:
    database_path = Path(app.config["DATABASE"])
    database_path.parent.mkdir(parents=True, exist_ok=True)
    with app.app_context():
        db = get_db()
        schema = (BASE_DIR / "schema.sql").read_text(encoding="utf-8")
        db.executescript(schema)
        seed_demo_data(db)
        db.commit()


def ensure_runtime_schema(app: Flask) -> None:
    database_path = Path(app.config["DATABASE"])
    database_path.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(database_path) as db:
        db.executescript(
            """
            CREATE TABLE IF NOT EXISTS user_sessions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                profile_id INTEGER,
                user_label TEXT NOT NULL DEFAULT 'anonymous-user',
                triage_level TEXT NOT NULL DEFAULT 'pending',
                safety_triggered INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (profile_id) REFERENCES user_profiles (id)
            );
            CREATE TABLE IF NOT EXISTS symptom_inputs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                primary_symptom TEXT NOT NULL,
                duration TEXT NOT NULL,
                severity INTEGER NOT NULL,
                additional_context TEXT,
                red_flags TEXT NOT NULL DEFAULT '[]',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (session_id) REFERENCES user_sessions (id)
            );
            CREATE TABLE IF NOT EXISTS followup_questions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                question_text TEXT NOT NULL,
                answer_text TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (session_id) REFERENCES user_sessions (id)
            );
            CREATE TABLE IF NOT EXISTS symptom_summaries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                main_complaint TEXT NOT NULL,
                structured_summary TEXT NOT NULL,
                triage_level TEXT NOT NULL,
                next_steps TEXT NOT NULL,
                disclaimer TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (session_id) REFERENCES user_sessions (id)
            );
            CREATE TABLE IF NOT EXISTS user_profiles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                display_name TEXT,
                age INTEGER,
                sex TEXT,
                height_cm REAL,
                weight_kg REAL,
                allergies TEXT,
                current_medications TEXT,
                chronic_conditions TEXT,
                past_history TEXT,
                family_history TEXT,
                emergency_contact TEXT,
                consent_use_history INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS health_records (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                profile_id INTEGER NOT NULL DEFAULT 1,
                record_type TEXT NOT NULL DEFAULT 'checkup',
                title TEXT NOT NULL,
                record_date TEXT,
                source_text TEXT,
                structured_content TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (profile_id) REFERENCES user_profiles (id)
            );
            """
        )
        session_columns = {row[1] for row in db.execute("PRAGMA table_info(user_sessions)").fetchall()}
        if "profile_id" not in session_columns:
            db.execute("ALTER TABLE user_sessions ADD COLUMN profile_id INTEGER")
        db.execute("INSERT OR IGNORE INTO user_profiles (id, display_name) VALUES (1, 'Demo User')")


def seed_demo_data(db: sqlite3.Connection) -> None:
    db.execute("INSERT INTO user_profiles (id, display_name, consent_use_history) VALUES (1, 'Demo User', 0)")
    cursor = db.execute(
        """
        INSERT INTO user_sessions (profile_id, user_label, triage_level, safety_triggered)
        VALUES (?, ?, ?, ?)
        """,
        (1, "demo-user", "routine", 0),
    )
    session_id = int(cursor.lastrowid)
    db.execute(
        """
        INSERT INTO symptom_inputs
            (session_id, primary_symptom, duration, severity, additional_context, red_flags)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            session_id,
            "Headache",
            "One day",
            4,
            "No severe red flags reported in this demo record.",
            "[]",
        ),
    )
    questions = [
        "When did the symptom start?",
        "Is the symptom getting better, worse, or staying the same?",
        "Are there any associated symptoms?",
    ]
    for question in questions:
        db.execute(
            "INSERT INTO followup_questions (session_id, question_text) VALUES (?, ?)",
            (session_id, question),
        )
    db.execute(
        """
        INSERT INTO symptom_summaries
            (session_id, main_complaint, structured_summary, triage_level, next_steps, disclaimer)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            session_id,
            "Headache",
            "Demo summary: headache for one day, moderate severity, no emergency keywords reported.",
            "routine",
            "Consider booking a routine appointment or seeking professional advice if symptoms persist.",
            DISCLAIMER_TEXT,
        ),
    )


def row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    return {key: row[key] for key in row.keys()}


def optional_row_to_dict(row: sqlite3.Row | None) -> dict[str, Any] | None:
    return row_to_dict(row) if row is not None else None


def require_fields(payload: dict[str, Any], required_fields: list[str]) -> tuple[bool, list[str]]:
    missing = [field for field in required_fields if not str(payload.get(field, "")).strip()]
    return not missing, missing


def register_routes(app: Flask) -> None:
    @app.route("/")
    def index() -> str:
        db = get_db()
        session_count = db.execute("SELECT COUNT(*) FROM user_sessions").fetchone()[0]
        safety_count = db.execute("SELECT COUNT(*) FROM user_sessions WHERE safety_triggered = 1").fetchone()[0]
        summary_count = db.execute("SELECT COUNT(*) FROM symptom_summaries").fetchone()[0]
        recent_sessions = db.execute(
            """
            SELECT user_sessions.*, symptom_inputs.primary_symptom
            FROM user_sessions
            LEFT JOIN symptom_inputs ON symptom_inputs.session_id = user_sessions.id
            ORDER BY user_sessions.created_at DESC, user_sessions.id DESC
            LIMIT 3
            """
        ).fetchall()
        return render_template(
            "index.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            session_count=session_count,
            safety_count=safety_count,
            summary_count=summary_count,
            recent_sessions=recent_sessions,
        )

    @app.route("/symptom-input", methods=["GET", "POST"])
    def symptom_input_page():
        profiles = get_profiles()
        mode = request.args.get("mode", "").strip()
        selected_profile_id = nullable_int(request.args.get("profile_id"))
        selected_profile = get_profile(selected_profile_id) if selected_profile_id else None
        selected_record_count = len(get_health_records(selected_profile_id)) if selected_profile_id else 0
        intake_ready = mode == "quick" or (mode == "profile" and selected_profile is not None)
        if request.method == "POST":
            payload = request.form.to_dict()
            form_profile_id = nullable_int(payload.get("profile_id"))
            if form_profile_id:
                profile = get_profile(form_profile_id)
                if profile is not None:
                    payload["profile_id"] = form_profile_id
                    payload["user_label"] = profile["display_name"] or f"profile-{form_profile_id}"
            ok, missing = require_fields(payload, ["primary_symptom", "duration", "severity"])
            if not ok:
                return render_template(
                    "symptom_input.html",
                    disclaimer=DISCLAIMER_TEXT,
                    brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
                    profiles=profiles,
                    selected_profile=selected_profile,
                    selected_record_count=selected_record_count,
                    intake_mode=mode or payload.get("intake_mode", ""),
                    intake_ready=True,
                    error=f"Missing: {', '.join(missing)}",
                ), 400
            session_result = create_symptom_session(payload)
            if session_result["safety_triggered"]:
                return redirect(url_for("safety_notice_page", session_id=session_result["session_id"]))
            return redirect(url_for("followup_questions_page", session_id=session_result["session_id"]))
        return render_template(
            "symptom_input.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            profiles=profiles,
            selected_profile=selected_profile,
            selected_record_count=selected_record_count,
            intake_mode=mode,
            intake_ready=intake_ready,
        )

    @app.route("/followup/<int:session_id>", methods=["GET", "POST"])
    def followup_questions_page(session_id: int):
        session = get_session(session_id)
        if session is None:
            abort(404)
        if request.method == "POST":
            for key, answer in request.form.items():
                if key.startswith("question_"):
                    question_id = int(key.replace("question_", ""))
                    save_followup_answer(session_id, question_id, answer)
            try:
                summary_id = create_symptom_summary(session_id)
            except LiveAIRequiredError:
                summary_id = None
            return redirect(url_for("symptom_summary_page", session_id=session_id, summary_id=summary_id))

        questions = get_questions(session_id)
        if not questions:
            for question in generate_followup_questions(get_symptom_input(session_id)):
                insert_followup_question(session_id, question)
            questions = get_questions(session_id)
        return render_template(
            "followup_questions.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            session=session,
            questions=questions,
        )

    @app.route("/summary/<int:session_id>")
    def symptom_summary_page(session_id: int):
        session = get_session(session_id)
        if session is None:
            abort(404)
        summary = get_latest_summary(session_id)
        ai_error = None
        if summary is None:
            try:
                create_symptom_summary(session_id)
            except LiveAIRequiredError as error:
                ai_error = build_live_ai_error("symptom_summary", str(error))
            summary = get_latest_summary(session_id)
        symptom = get_symptom_input(session_id)
        questions = get_questions(session_id)
        answered_questions = [
            question for question in questions if str(question["answer_text"] or "").strip()
        ]
        return render_template(
            "symptom_summary.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            session=session,
            symptom=symptom,
            questions=questions,
            answered_questions=answered_questions,
            summary=summary,
            ai_error=ai_error,
        )

    @app.route("/care-guidance/<int:session_id>")
    def care_guidance_page(session_id: int):
        session = get_session(session_id)
        if session is None:
            abort(404)
        symptom = get_symptom_input(session_id)
        summary = get_latest_summary(session_id)
        ai_error = None
        guidance = None
        if summary is None:
            try:
                create_symptom_summary(session_id)
            except LiveAIRequiredError as error:
                ai_error = build_live_ai_error("symptom_summary", str(error))
            summary = get_latest_summary(session_id)
        if ai_error is None:
            try:
                guidance = generate_care_guidance(session_id)
            except LiveAIRequiredError as error:
                ai_error = build_live_ai_error("care_guidance", str(error))
        return render_template(
            "care_guidance.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            session=session,
            symptom=symptom,
            summary=summary,
            guidance=guidance,
            ai_error=ai_error,
        )

    @app.route("/profile")
    def profile_page():
        return render_template(
            "profile.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            profiles=get_profiles(),
        )

    @app.route("/profile/new", methods=["GET", "POST"])
    def new_profile_page():
        if request.method == "POST":
            profile_id = save_profile(request.form.to_dict())
            source_text = str(request.form.get("source_text") or "").strip()
            if source_text:
                save_health_record(
                    {
                        "profile_id": profile_id,
                        "title": request.form.get("record_title") or "Imported checkup record",
                        "record_date": request.form.get("record_date") or "",
                        "record_type": request.form.get("record_type") or "checkup",
                        "source_text": source_text,
                        "structured_content": json.dumps(structure_health_record(source_text), ensure_ascii=False, indent=2),
                    }
                )
            return redirect(url_for("edit_profile_page", profile_id=profile_id))
        return render_template(
            "profile_form.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            profile=None,
            records=[],
            form_title="Create New Profile",
            form_intro="Add a new local demo user before starting personalized AI intake.",
            submit_label="Save New Profile",
        )

    @app.route("/profile/<int:profile_id>", methods=["GET", "POST"])
    def edit_profile_page(profile_id: int):
        profile = get_profile(profile_id)
        if profile is None:
            abort(404)
        if request.method == "POST":
            save_profile(request.form.to_dict(), profile_id=profile_id)
            source_text = str(request.form.get("source_text") or "").strip()
            if source_text:
                save_health_record(
                    {
                        "profile_id": profile_id,
                        "title": request.form.get("record_title") or "Imported checkup record",
                        "record_date": request.form.get("record_date") or "",
                        "record_type": request.form.get("record_type") or "checkup",
                        "source_text": source_text,
                        "structured_content": json.dumps(structure_health_record(source_text), ensure_ascii=False, indent=2),
                    }
                )
            return redirect(url_for("edit_profile_page", profile_id=profile_id))
        return render_template(
            "profile_form.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            profile=profile,
            records=get_health_records(profile_id),
            form_title="Edit Health Profile",
            form_intro="Review a saved local demo profile, update history, and structure pasted checkup text.",
            submit_label="Save Profile",
        )

    @app.route("/safety-notice")
    @app.route("/safety-notice/<int:session_id>")
    def safety_notice_page(session_id: int | None = None):
        session = get_session(session_id) if session_id else None
        symptom = get_symptom_input(session_id) if session_id else None
        return render_template(
            "safety_notice.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
            session=session,
            symptom=symptom,
        )

    @app.route("/uml-generator")
    def uml_generator_page() -> str:
        return render_template(
            "uml_generator.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
        )

    @app.route("/about")
    def about_page() -> str:
        return render_template(
            "about.html",
            disclaimer=DISCLAIMER_TEXT,
            brief_disclaimer=BRIEF_DISCLAIMER_TEXT,
        )

    @app.get("/api/health")
    def api_health():
        return jsonify(
            {
                "status": "ok",
                "service": "ai-symptom-intake-triage-support",
                "ai_configured": bool(current_app.config.get("AI_API_KEY")),
                "ai_provider": current_app.config.get("AI_PROVIDER"),
                "ai_model": current_app.config.get("AI_MODEL"),
                "ai_base_url": current_app.config.get("AI_BASE_URL"),
                "ai_last_error": current_app.config.get("AI_LAST_ERROR"),
            }
        )

    @app.get("/api/ai/models")
    def api_ai_models():
        if not current_app.config.get("AI_API_KEY"):
            return jsonify({"error": "missing_api_key", "message": "Set APIFREE_API_KEY before listing models."}), 400
        result, status_code = list_ai_models()
        return jsonify(result), status_code

    @app.post("/api/ai/test")
    def api_ai_test():
        if not current_app.config.get("AI_API_KEY"):
            return jsonify({"error": "missing_api_key", "message": "Set APIFREE_API_KEY before testing the model."}), 400
        result = call_model_json(
            'Return JSON exactly as {"ok": true, "message": "model reachable"} and nothing else.'
        )
        if result.get("ok") is True:
            return jsonify(
                {
                    "ok": True,
                    "message": result.get("message", "model reachable"),
                    "provider": current_app.config.get("AI_PROVIDER"),
                    "model": current_app.config.get("AI_MODEL"),
                    "base_url": current_app.config.get("AI_BASE_URL"),
                }
            )
        return jsonify(
            {
                "ok": False,
                "error": current_app.config.get("AI_LAST_ERROR") or "model_test_failed",
                "provider": current_app.config.get("AI_PROVIDER"),
                "model": current_app.config.get("AI_MODEL"),
                "base_url": current_app.config.get("AI_BASE_URL"),
            }
        ), 502

    @app.post("/api/symptoms")
    def api_create_symptom():
        payload = request.get_json(silent=True) or {}
        ok, missing = require_fields(payload, ["primary_symptom", "duration", "severity"])
        if not ok:
            return jsonify({"error": "missing_required_fields", "fields": missing}), 400
        result = create_symptom_session(payload)
        status_code = 201
        return jsonify(result), status_code

    @app.post("/api/intake-chat")
    def api_intake_chat():
        payload = request.get_json(silent=True) or {}
        history = payload.get("history") or []
        message = str(payload.get("message") or "").strip()
        requested_model_history = bool(payload.get("allow_model_history"))
        profile_id = nullable_int(payload.get("profile_id"))
        profile = get_profile(profile_id) if profile_id else None
        allow_model_history = requested_model_history and bool(profile and profile["consent_use_history"])
        if not message:
            return jsonify({"error": "missing_required_fields", "fields": ["message"]}), 400
        if not isinstance(history, list):
            history = []
        history = normalize_chat_history(history)
        history.append({"role": "user", "content": message})

        combined_text = " ".join(item["content"] for item in history if item["role"] == "user")
        severity = parse_severity_from_text(combined_text)
        red_flags = detect_red_flags(combined_text, severity)
        if red_flags:
            session_result = create_symptom_session(
                {
                    "profile_id": profile_id,
                    "user_label": (profile["display_name"] if profile else "anonymous-user"),
                    "primary_symptom": extract_primary_symptom(history),
                    "duration": extract_duration(combined_text),
                    "severity": max(severity, 9),
                    "additional_context": combined_text,
                }
            )
            return jsonify(
                {
                    "assistant_message": (
                        "Some answers match safety warning signs. Please seek urgent professional medical help. "
                        "I will show the safety notice and keep the guidance non-diagnostic."
                    ),
                    "complete": True,
                    "safety_triggered": True,
                    "session_id": session_result["session_id"],
                    "next_url": session_result["next_url"],
                    "care_guidance_url": url_for("care_guidance_page", session_id=session_result["session_id"]),
                    "history": history,
                    "ai_source": "safety_rules",
                    "ai_configured": bool(current_app.config.get("AI_API_KEY")),
                    "profile_context_used": False,
                    "profile_context_blocked": bool(requested_model_history and profile and not profile["consent_use_history"]),
                    "disclaimer": DISCLAIMER_TEXT,
                }
            )

        try:
            chat_result = generate_intake_chat_reply(
                history,
                allow_model_history=allow_model_history,
                profile_id=profile_id,
            )
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("intake_chat", str(error))), 503
        if chat_result["complete"]:
            extracted = chat_result["extracted"]
            if profile is not None:
                extracted["profile_id"] = profile_id
                extracted["user_label"] = profile["display_name"] or f"profile-{profile_id}"
            session_result = create_symptom_session(extracted)
            try:
                summary_id = create_symptom_summary(session_result["session_id"])
            except LiveAIRequiredError as error:
                return jsonify(build_live_ai_error("symptom_summary", str(error))), 503
            return jsonify(
                {
                    "assistant_message": chat_result["assistant_message"],
                    "complete": True,
                    "safety_triggered": session_result["safety_triggered"],
                    "session_id": session_result["session_id"],
                    "summary_id": summary_id,
                    "next_url": url_for("symptom_summary_page", session_id=session_result["session_id"]),
                    "care_guidance_url": url_for("care_guidance_page", session_id=session_result["session_id"]),
                    "history": history,
                    "ai_source": chat_result.get("source", "unknown"),
                    "ai_configured": bool(current_app.config.get("AI_API_KEY")),
                    "profile_context_used": allow_model_history,
                    "profile_context_blocked": bool(requested_model_history and profile and not profile["consent_use_history"]),
                    "disclaimer": DISCLAIMER_TEXT,
                }
            )
        history.append({"role": "assistant", "content": chat_result["assistant_message"]})
        return jsonify(
            {
                "assistant_message": chat_result["assistant_message"],
                "complete": False,
                "safety_triggered": False,
                "history": history,
                "ai_source": chat_result.get("source", "unknown"),
                "ai_configured": bool(current_app.config.get("AI_API_KEY")),
                "profile_context_used": allow_model_history,
                "profile_context_blocked": bool(requested_model_history and profile and not profile["consent_use_history"]),
                "disclaimer": DISCLAIMER_TEXT,
            }
        )

    @app.post("/api/followup-questions")
    def api_followup_questions():
        payload = request.get_json(silent=True) or {}
        session_id = payload.get("session_id")
        if session_id:
            symptom = get_symptom_input(int(session_id))
            if symptom is None:
                return jsonify({"error": "session_not_found"}), 404
        else:
            ok, missing = require_fields(payload, ["primary_symptom"])
            if not ok:
                return jsonify({"error": "missing_required_fields", "fields": missing}), 400
            symptom = payload
        questions = generate_followup_questions(symptom)
        return jsonify({"questions": questions, "disclaimer": DISCLAIMER_TEXT})

    @app.post("/api/sessions/<int:session_id>/followup")
    def api_session_followup(session_id: int):
        symptom = get_symptom_input(session_id)
        if symptom is None:
            return jsonify({"error": "session_not_found"}), 404
        existing_questions = get_questions(session_id)
        if not existing_questions:
            for question in generate_followup_questions(symptom):
                insert_followup_question(session_id, question)
            existing_questions = get_questions(session_id)
        return jsonify(
            {
                "session_id": session_id,
                "questions": [row_to_dict(question) for question in existing_questions],
                "disclaimer": DISCLAIMER_TEXT,
            }
        )

    @app.post("/api/summary")
    def api_summary():
        payload = request.get_json(silent=True) or {}
        session_id = payload.get("session_id")
        if not session_id:
            return jsonify({"error": "missing_required_fields", "fields": ["session_id"]}), 400
        session = get_session(int(session_id))
        if session is None:
            return jsonify({"error": "session_not_found"}), 404
        for answer in payload.get("answers", []):
            if isinstance(answer, dict) and answer.get("question_id"):
                save_followup_answer(int(session_id), int(answer["question_id"]), str(answer.get("answer", "")))
        try:
            summary_id = create_symptom_summary(int(session_id))
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("symptom_summary", str(error))), 503
        return jsonify(row_to_dict(get_summary(summary_id)))

    @app.post("/api/sessions/<int:session_id>/summary")
    def api_session_summary(session_id: int):
        session = get_session(session_id)
        if session is None:
            return jsonify({"error": "session_not_found"}), 404
        payload = request.get_json(silent=True) or {}
        for answer in payload.get("answers", []):
            if isinstance(answer, dict) and answer.get("question_id"):
                save_followup_answer(session_id, int(answer["question_id"]), str(answer.get("answer", "")))
        try:
            summary_id = create_symptom_summary(session_id)
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("symptom_summary", str(error))), 503
        return jsonify(row_to_dict(get_summary(summary_id)))

    @app.post("/api/care-guidance")
    def api_care_guidance():
        payload = request.get_json(silent=True) or {}
        session_id = payload.get("session_id")
        if not session_id:
            return jsonify({"error": "missing_required_fields", "fields": ["session_id"]}), 400
        session = get_session(int(session_id))
        if session is None:
            return jsonify({"error": "session_not_found"}), 404
        try:
            return jsonify(generate_care_guidance(int(session_id)))
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("care_guidance", str(error))), 503

    @app.post("/api/sessions/<int:session_id>/care-guidance")
    def api_session_care_guidance(session_id: int):
        session = get_session(session_id)
        if session is None:
            return jsonify({"error": "session_not_found"}), 404
        try:
            return jsonify(generate_care_guidance(session_id))
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("care_guidance", str(error))), 503

    @app.get("/api/profile")
    def api_get_profile():
        profile_id = nullable_int(request.args.get("profile_id"))
        profile = get_profile(profile_id)
        return jsonify(
            {
                "profile": optional_row_to_dict(profile),
                "profiles": [row_to_dict(row) for row in get_profiles()],
            }
        )

    @app.post("/api/uml/generate")
    def api_generate_uml():
        payload = request.get_json(silent=True) or {}
        business_problem = str(payload.get("business_problem") or "").strip()
        diagram_type = str(payload.get("diagram_type") or "activity").strip().lower()
        if not business_problem:
            return jsonify({"error": "missing_required_fields", "fields": ["business_problem"]}), 400
        if diagram_type not in {"use_case", "activity", "class", "sequence"}:
            return jsonify({"error": "invalid_diagram_type"}), 400
        try:
            return jsonify(generate_uml_diagram(diagram_type, business_problem))
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("uml_generation", str(error))), 503

    @app.post("/api/profile")
    def api_save_profile():
        payload = request.get_json(silent=True) or {}
        profile_id = save_profile(payload, profile_id=nullable_int(payload.get("profile_id")))
        return jsonify(row_to_dict(get_profile(profile_id)))

    @app.post("/api/health-records/analyze")
    def api_analyze_health_record():
        payload = request.get_json(silent=True) or {}
        source_text = str(payload.get("source_text") or "").strip()
        if not source_text:
            return jsonify({"error": "missing_required_fields", "fields": ["source_text"]}), 400
        try:
            return jsonify(structure_health_record(source_text))
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("health_record_structure", str(error))), 503

    @app.post("/api/profiles/<int:profile_id>/checkup-structure")
    def api_profile_checkup_structure(profile_id: int):
        if get_profile(profile_id) is None:
            return jsonify({"error": "profile_not_found"}), 404
        payload = request.get_json(silent=True) or {}
        source_text = str(payload.get("source_text") or "").strip()
        if not source_text:
            return jsonify({"error": "missing_required_fields", "fields": ["source_text"]}), 400
        try:
            structured = structure_health_record(source_text)
        except LiveAIRequiredError as error:
            return jsonify(build_live_ai_error("health_record_structure", str(error))), 503
        return jsonify({"profile_id": profile_id, "structured_record": structured, "disclaimer": DISCLAIMER_TEXT})

    @app.post("/api/health-records")
    def api_save_health_record():
        payload = request.get_json(silent=True) or {}
        ok, missing = require_fields(payload, ["title"])
        if not ok:
            return jsonify({"error": "missing_required_fields", "fields": missing}), 400
        record_id = save_health_record(payload)
        return jsonify(row_to_dict(get_health_record(record_id))), 201


def create_symptom_session(payload: dict[str, Any]) -> dict[str, Any]:
    severity = parse_severity(payload.get("severity"))
    combined_text = " ".join(
        [
            str(payload.get("primary_symptom", "")),
            str(payload.get("duration", "")),
            str(payload.get("additional_context", "")),
        ]
    )
    red_flags = detect_red_flags(combined_text, severity)
    safety_triggered = bool(red_flags)
    triage_level = "urgent" if safety_triggered else triage_level_from_severity(severity)
    profile_id = nullable_int(payload.get("profile_id"))
    user_label = payload.get("user_label") or "anonymous-user"

    db = get_db()
    cursor = db.execute(
        "INSERT INTO user_sessions (profile_id, user_label, triage_level, safety_triggered) VALUES (?, ?, ?, ?)",
        (profile_id, user_label, triage_level, int(safety_triggered)),
    )
    session_id = int(cursor.lastrowid)
    db.execute(
        """
        INSERT INTO symptom_inputs
            (session_id, primary_symptom, duration, severity, additional_context, red_flags)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            session_id,
            payload["primary_symptom"],
            payload["duration"],
            severity,
            payload.get("additional_context", ""),
            json.dumps(red_flags),
        ),
    )
    if not safety_triggered:
        for question in generate_followup_questions(
            {
                "primary_symptom": payload["primary_symptom"],
                "duration": payload["duration"],
                "severity": severity,
                "additional_context": payload.get("additional_context", ""),
            }
        ):
            insert_followup_question(session_id, question)
    db.commit()
    return {
        "session_id": session_id,
        "triage_level": triage_level,
        "safety_triggered": safety_triggered,
        "red_flags": red_flags,
        "questions": [row["question_text"] for row in get_questions(session_id)] if not safety_triggered else [],
        "disclaimer": DISCLAIMER_TEXT,
        "next_url": url_for("safety_notice_page", session_id=session_id)
        if safety_triggered
        else url_for("followup_questions_page", session_id=session_id),
    }


def parse_severity(value: Any) -> int:
    try:
        return max(0, min(10, int(value)))
    except (TypeError, ValueError):
        return 0


def parse_severity_from_text(text: str) -> int:
    explicit = re.search(r"\b(10|[0-9])\s*/\s*10\b", text)
    if explicit:
        return parse_severity(explicit.group(1))
    number = re.search(r"\b(?:severity|pain|程度|疼痛)[^\d]*(10|[0-9])\b", text, re.IGNORECASE)
    if number:
        return parse_severity(number.group(1))
    if re.search(r"\b(severe|worst|unbearable|剧烈|严重|难以忍受)\b", text, re.IGNORECASE):
        return 8
    if re.search(r"\b(mild|slight|轻微)\b", text, re.IGNORECASE):
        return 2
    return 4


def detect_red_flags(text: str, severity: int) -> list[str]:
    normalized = text.lower()
    matched = []
    for rule_name, pattern in RED_FLAG_RULES:
        for match in re.finditer(pattern, normalized, re.IGNORECASE):
            if not is_negated_match(normalized, match.start()):
                matched.append(rule_name)
                break
    if severity >= 9:
        matched.append("very_high_severity")
    return sorted(set(matched))


def is_negated_match(text: str, match_start: int) -> bool:
    prefix = text[max(0, match_start - 28) : match_start]
    return bool(re.search(r"\b(no|not|without|deny|denies|denied|没有|无|未|不)\b\s*$", prefix, re.IGNORECASE))


def triage_level_from_severity(severity: int) -> str:
    if severity >= 7:
        return "soon"
    if severity >= 4:
        return "routine"
    return "self_monitor"


def generate_followup_questions(symptom: dict[str, Any] | sqlite3.Row | None) -> list[str]:
    symptom_dict = dict(symptom) if symptom else {}
    analyzer = current_app.config.get("AI_FOLLOWUP_GENERATOR")
    if analyzer:
        return analyzer(symptom_dict)

    prompt = (
        "Generate 5 concise non-diagnostic follow-up questions for a symptom intake form. "
        "Return JSON as {\"questions\": [\"...\"]}. "
        f"Symptom input: {json.dumps(symptom_dict, ensure_ascii=False)}"
    )
    model_result = call_model_json(prompt)
    if isinstance(model_result.get("questions"), list):
        return [str(question) for question in model_result["questions"][:5] if str(question).strip()]

    primary = str(symptom_dict.get("primary_symptom") or "this symptom").lower()
    return [
        f"When did {primary} start?",
        "Is it getting better, worse, or staying about the same?",
        "What makes it better or worse?",
        "Are there any associated symptoms such as fever, dizziness, nausea, rash, or pain elsewhere?",
        "Have you taken any medicine or received professional advice for this symptom?",
    ]


def normalize_chat_history(history: list[Any]) -> list[dict[str, str]]:
    cleaned = []
    for item in history[-12:]:
        if not isinstance(item, dict):
            continue
        role = item.get("role")
        content = str(item.get("content") or "").strip()
        if role in {"user", "assistant"} and content:
            cleaned.append({"role": role, "content": content[:1200]})
    return cleaned


def generate_intake_chat_reply(
    history: list[dict[str, str]],
    allow_model_history: bool = False,
    profile_id: int | None = None,
) -> dict[str, Any]:
    generator = current_app.config.get("AI_INTAKE_CHAT_GENERATOR")
    if generator:
        return generator(history)

    model_history = history[-14:]
    profile_context = build_model_profile_context(profile_id or 1) if allow_model_history else {}
    prompt = (
        "You are a careful AI symptom intake assistant for a medical pre-consultation website. "
        "Use the full current chat history to avoid repeating questions and to summarize accurately. "
        "Ask one concise follow-up question at a time until enough context is collected for non-diagnostic care guidance. "
        "Return strict JSON with keys: assistant_message, complete, extracted, missing_fields. "
        "extracted must contain primary_symptom, duration, severity, additional_context, associated_symptoms, "
        "medicines_taken, allergies, relevant_history, user_concerns. "
        "Do not diagnose, prescribe, give exact medication doses, or claim certainty. "
        "Ask about duration, severity, location, onset, trend, associated symptoms, current medicines, allergies, "
        "pregnancy if relevant, existing conditions, and red flags before completing. "
        "If the user writes Chinese, answer in Chinese. If the user writes English, answer in English. "
        "If at least primary symptom, duration, severity, associated symptoms or absence, medicines/allergies, "
        "and relevant history are available, set complete=true and write a concise final assistant_message. "
        f"Saved profile permission: {allow_model_history}. "
        f"Profile context if permitted: {json.dumps(profile_context, ensure_ascii=False)} "
        f"Full current intake chat history: {json.dumps(model_history, ensure_ascii=False)}"
    )
    model_result = call_model_json(prompt, required=True)
    if model_result.get("assistant_message"):
        complete = bool(model_result.get("complete"))
        extracted = normalize_extracted_symptom(model_result.get("extracted") or {}, history)
        return {
            "assistant_message": str(model_result["assistant_message"])[:700],
            "complete": complete,
            "extracted": extracted,
            "source": "ai_model",
            "missing_fields": model_result.get("missing_fields") or [],
        }
    current_app.config["AI_LAST_ERROR"] = "model_response_missing_assistant_message"
    raise LiveAIRequiredError("APIFree returned JSON, but it did not include assistant_message.")


def fallback_intake_chat_reply(history: list[dict[str, str]]) -> dict[str, Any]:
    user_turns = [item["content"] for item in history if item["role"] == "user"]
    combined = " ".join(user_turns)
    symptom_hint = extract_primary_symptom(history) or "this symptom"
    duration_known = bool(re.search(r"\b(hour|hours|day|days|week|weeks|month|months|today|yesterday|morning|night)\b|小时|天|周|月|今天|昨天|早上|晚上", combined, re.IGNORECASE))
    severity_known = parse_severity_from_text(combined) > 0
    medicine_known = bool(re.search(r"\b(medicine|medication|drug|allergy|allergic|ibuprofen|paracetamol|acetaminophen|aspirin)\b|药|过敏|布洛芬|对乙酰氨基酚", combined, re.IGNORECASE))
    associated_known = bool(re.search(r"\b(fever|nausea|dizzy|dizziness|rash|vomit|breath|pain)\b|发烧|恶心|头晕|皮疹|呕吐|呼吸|疼", combined, re.IGNORECASE))
    prompts = []
    if not duration_known:
        prompts.append(f"How long has {symptom_hint} been happening, and did it start suddenly or gradually?")
    if not severity_known:
        prompts.append(f"On a scale of 0 to 10, how severe is {symptom_hint} right now?")
    if not associated_known:
        prompts.append("Are there any associated symptoms, such as fever, dizziness, nausea, rash, pain elsewhere, vomiting, or trouble breathing?")
    if not medicine_known:
        prompts.append("Have you taken any medicines, and do you have allergies, pregnancy, chronic conditions, recent injury, or unusual exposure?")
    if not prompts:
        prompts.append("What has changed since the symptom started, and what makes it better or worse?")
    if len(user_turns) <= len(prompts):
        return {"assistant_message": prompts[len(user_turns) - 1], "complete": False, "extracted": {}, "source": "fallback"}

    extracted = normalize_extracted_symptom({}, history)
    return {
        "assistant_message": (
            "Thanks. I have enough information to create a structured summary and safe care guidance. "
            "Please review everything before acting."
        ),
        "complete": True,
        "extracted": extracted,
        "source": "fallback",
    }


def normalize_extracted_symptom(extracted: dict[str, Any], history: list[dict[str, str]]) -> dict[str, Any]:
    user_text = " ".join(item["content"] for item in history if item["role"] == "user")
    context_parts = [
        ("full_chat_notes", extracted.get("additional_context") or user_text),
        ("associated_symptoms", extracted.get("associated_symptoms")),
        ("medicines_taken", extracted.get("medicines_taken")),
        ("allergies", extracted.get("allergies")),
        ("relevant_history", extracted.get("relevant_history")),
        ("user_concerns", extracted.get("user_concerns")),
    ]
    additional_context = "\n".join(
        f"{label}: {str(value).strip()}"
        for label, value in context_parts
        if str(value or "").strip()
    )
    return {
        "primary_symptom": str(extracted.get("primary_symptom") or extract_primary_symptom(history)).strip(),
        "duration": str(extracted.get("duration") or extract_duration(user_text)).strip(),
        "severity": parse_severity(extracted.get("severity") or parse_severity_from_text(user_text)),
        "additional_context": additional_context.strip() or user_text.strip(),
    }


def extract_primary_symptom(history: list[dict[str, str]]) -> str:
    for item in history:
        if item["role"] == "user":
            text = item["content"].strip()
            return text[:120] or "Unspecified symptom"
    return "Unspecified symptom"


def extract_duration(text: str) -> str:
    duration = re.search(
        r"\b(\d+\s*(?:minutes?|hours?|days?|weeks?|months?)|today|yesterday|this morning|tonight|刚刚|今天|昨天|[一二三四五六七八九十\d]+天)\b",
        text,
        re.IGNORECASE,
    )
    return duration.group(1) if duration else "Not clearly specified"


def create_symptom_summary(session_id: int) -> int:
    symptom = get_symptom_input(session_id)
    if symptom is None:
        raise ValueError("symptom input not found")
    questions = get_questions(session_id)
    answers = [{"question": row["question_text"], "answer": row["answer_text"] or ""} for row in questions]
    red_flags = json.loads(symptom["red_flags"] or "[]")
    triage_level = "urgent" if red_flags else triage_level_from_severity(int(symptom["severity"]))

    summary = generate_summary_text(symptom, answers, red_flags, triage_level)
    next_steps = next_steps_for_triage(triage_level)
    db = get_db()
    cursor = db.execute(
        """
        INSERT INTO symptom_summaries
            (session_id, main_complaint, structured_summary, triage_level, next_steps, disclaimer)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (session_id, symptom["primary_symptom"], summary, triage_level, next_steps, DISCLAIMER_TEXT),
    )
    db.execute(
        "UPDATE user_sessions SET triage_level = ?, safety_triggered = ? WHERE id = ?",
        (triage_level, int(bool(red_flags)), session_id),
    )
    db.commit()
    return int(cursor.lastrowid)


def generate_summary_text(symptom: sqlite3.Row, answers: list[dict[str, str]], red_flags: list[str], triage_level: str) -> str:
    generator = current_app.config.get("AI_SUMMARY_GENERATOR")
    if generator:
        return generator(dict(symptom), answers, red_flags, triage_level)

    prompt = (
        "Create a precise structured symptom summary for a triage-support website. "
        "Use only the user-provided facts. Do not invent missing details. Do not diagnose. Do not prescribe. "
        "Return JSON as {\"summary\": \"...\"}. The summary must include: chief complaint, onset/duration, "
        "severity, location if stated, symptom trend, associated symptoms or denied symptoms, medicines already "
        "taken, allergies, relevant health history/profile context, red-flag status, and what remains unknown. "
        "Write in the same language as the user's symptom text when possible. "
        f"Symptom: {json.dumps(dict(symptom), ensure_ascii=False)} "
        f"Follow-up answers: {json.dumps(answers, ensure_ascii=False)} "
        f"Red flags: {json.dumps(red_flags)} Triage level: {triage_level}"
    )
    live_ai_expected = bool(current_app.config.get("AI_API_KEY"))
    model_result = call_model_json(prompt, required=live_ai_expected)
    if model_result.get("summary"):
        return str(model_result["summary"])
    if live_ai_expected:
        current_app.config["AI_LAST_ERROR"] = "model_response_missing_summary"
        raise LiveAIRequiredError("APIFree returned JSON, but it did not include summary.")

    answer_lines = "; ".join(
        f"{item['question']} Answer: {item['answer'] or 'not provided'}" for item in answers
    )
    red_flag_note = f" Safety flags detected: {', '.join(red_flags)}." if red_flags else " No emergency keywords were detected by the safety rules."
    return (
        f"Chief complaint: {symptom['primary_symptom']}. "
        f"Duration/onset: {symptom['duration']}. Severity: {symptom['severity']}/10. "
        f"User-provided context: {symptom['additional_context'] or 'not provided'}. "
        f"Follow-up responses: {answer_lines or 'not yet provided'}. "
        f"Safety-rule result:{red_flag_note} "
        "Unknown items should be confirmed with the user or a healthcare professional before making care decisions."
    )


def generate_care_guidance(session_id: int) -> dict[str, Any]:
    symptom = get_symptom_input(session_id)
    summary = get_latest_summary(session_id)
    if symptom is None:
        raise ValueError("symptom input not found")

    red_flags = json.loads(symptom["red_flags"] or "[]")
    triage_level = summary["triage_level"] if summary else ("urgent" if red_flags else triage_level_from_severity(int(symptom["severity"])))
    session = get_session(session_id)
    profile_context = build_model_profile_context(session["profile_id"]) if session and session["profile_id"] else {}
    generator = current_app.config.get("AI_CARE_GUIDANCE_GENERATOR")
    if generator:
        return generator(dict(symptom), row_to_dict(summary) if summary else {}, red_flags, triage_level)

    prompt = (
        "Create specific, fact-based, safe, non-diagnostic care guidance for a symptom-intake website. "
        "Avoid generic filler. Ground every recommendation in the symptom summary, user context, red flags, "
        "profile information if provided, or explicitly mark it as something to ask a professional. "
        "Return JSON with keys: self_care, clinician_discussion, medication_discussion, "
        "monitoring, visit_preparation, avoid, medication_reference, care_plan_table, safety_note. "
        "medication_reference must be a list of objects with keys: option, purpose, suitability, dose_boundary, cautions. "
        "care_plan_table must be a list of objects with keys: priority, action, why, when_to_seek_help. "
        "Do not diagnose. Do not prescribe. Do not give exact drug doses, schedules, tablet counts, or Rx instructions. "
        "Medication items must be phrased as options to discuss with a licensed clinician or pharmacist. "
        f"Use this exact value for every dose_boundary: {DOSE_BOUNDARY_TEXT} "
        f"Symptom: {json.dumps(dict(symptom), ensure_ascii=False)} "
        f"Summary: {json.dumps(row_to_dict(summary) if summary else {}, ensure_ascii=False)} "
        f"Profile context if available: {json.dumps(profile_context, ensure_ascii=False)} "
        f"Red flags: {json.dumps(red_flags)} Triage level: {triage_level}"
    )
    live_ai_expected = bool(current_app.config.get("AI_API_KEY"))
    model_result = call_model_json(prompt, required=live_ai_expected)
    normalized = normalize_care_guidance(model_result)
    if normalized:
        if live_ai_expected:
            if not normalized.get("medication_reference") or not normalized.get("care_plan_table"):
                current_app.config["AI_LAST_ERROR"] = "model_response_missing_guidance_tables"
                raise LiveAIRequiredError(
                    "APIFree returned JSON, but it did not include medication_reference and care_plan_table."
                )
            normalized["medication_boundary"] = MEDICATION_BOUNDARY_TEXT
            normalized["mode"] = "ai_model"
            return normalized
        fallback = fallback_care_guidance(symptom, red_flags, triage_level)
        if not normalized.get("medication_reference"):
            normalized["medication_reference"] = fallback["medication_reference"]
        if not normalized.get("care_plan_table"):
            normalized["care_plan_table"] = fallback["care_plan_table"]
        normalized["medication_boundary"] = MEDICATION_BOUNDARY_TEXT
        normalized["mode"] = "ai_or_provider_fallback"
        return normalized
    return fallback_care_guidance(symptom, red_flags, triage_level)


def normalize_care_guidance(model_result: dict[str, Any]) -> dict[str, Any]:
    if not model_result:
        return {}

    def listify(value: Any) -> list[str]:
        if isinstance(value, list):
            return [str(item).strip() for item in value if str(item).strip()][:6]
        if isinstance(value, str) and value.strip():
            return [value.strip()]
        return []

    medication_reference = normalize_medication_reference(model_result.get("medication_reference"))
    care_plan_table = normalize_care_plan_table(model_result.get("care_plan_table"))
    return {
        "self_care": listify(model_result.get("self_care")),
        "clinician_discussion": listify(model_result.get("clinician_discussion")),
        "medication_discussion": listify(model_result.get("medication_discussion")),
        "monitoring": listify(model_result.get("monitoring")),
        "visit_preparation": listify(model_result.get("visit_preparation")),
        "avoid": listify(model_result.get("avoid")),
        "medication_reference": medication_reference,
        "care_plan_table": care_plan_table,
        "safety_note": str(model_result.get("safety_note") or DISCLAIMER_TEXT).strip(),
        "medication_boundary": MEDICATION_BOUNDARY_TEXT,
    }


def safe_guidance_text(value: Any, fallback: str = "Discuss this with a licensed clinician or pharmacist.") -> str:
    text = re.sub(r"\s+", " ", str(value or "").strip())
    if not text:
        return fallback
    if UNSAFE_DOSAGE_PATTERN.search(text):
        return fallback
    return text[:260]


def normalize_medication_reference(value: Any) -> list[dict[str, str]]:
    if not isinstance(value, list):
        return []
    rows: list[dict[str, str]] = []
    for item in value[:5]:
        if not isinstance(item, dict):
            continue
        rows.append(
            {
                "option": safe_guidance_text(item.get("option"), "Medication option to discuss"),
                "purpose": safe_guidance_text(item.get("purpose"), "Symptom relief discussion"),
                "suitability": safe_guidance_text(item.get("suitability"), "Depends on age, allergies, conditions, pregnancy status, and current medicines."),
                "dose_boundary": DOSE_BOUNDARY_TEXT,
                "cautions": safe_guidance_text(item.get("cautions"), "Check contraindications, interactions, and warnings before use."),
            }
        )
    return rows


def normalize_care_plan_table(value: Any) -> list[dict[str, str]]:
    if not isinstance(value, list):
        return []
    rows: list[dict[str, str]] = []
    for item in value[:6]:
        if not isinstance(item, dict):
            continue
        rows.append(
            {
                "priority": safe_guidance_text(item.get("priority"), "Next"),
                "action": safe_guidance_text(item.get("action"), "Review the symptom and consider professional advice."),
                "why": safe_guidance_text(item.get("why"), "Supports safer next-step planning."),
                "when_to_seek_help": safe_guidance_text(item.get("when_to_seek_help"), "Seek professional care if symptoms worsen, persist, or feel concerning."),
            }
        )
    return rows


def fallback_care_guidance(symptom: sqlite3.Row, red_flags: list[str], triage_level: str) -> dict[str, Any]:
    primary = str(symptom["primary_symptom"]).lower()
    urgent = triage_level == "urgent" or bool(red_flags)
    self_care = [
        "Rest in a safe place and avoid activities that make symptoms worse.",
        "Drink fluids if you can do so safely and have not been told to restrict fluids.",
        "Track when symptoms started, what changes them, and any associated symptoms.",
    ]
    if "cough" in primary or "sore throat" in primary:
        self_care.append("Consider warm fluids and avoiding smoke or strong irritants.")
    if "headache" in primary:
        self_care.append("Consider a quiet, dim environment and note any new neurological symptoms.")
    if "stomach" in primary or "abdominal" in primary or "nausea" in primary:
        self_care.append("Consider small sips of fluid and avoid heavy meals while symptoms are active.")

    if urgent:
        safety_note = "Safety rules were triggered. Seek urgent professional medical help rather than relying on online guidance."
    else:
        safety_note = "This is general support information, not a diagnosis or prescription. Ask a licensed professional before using medicines."

    medication_reference = build_fallback_medication_reference(primary, urgent)
    care_plan_table = build_fallback_care_plan_table(primary, urgent)

    return {
        "self_care": self_care,
        "clinician_discussion": [
            "Ask whether your symptoms require urgent care, routine clinic review, or monitoring.",
            "Ask which warning signs should make you seek urgent help.",
            "Ask whether any existing conditions, pregnancy, allergies, or current medicines change your options.",
        ],
        "medication_discussion": [
            "Ask a doctor or pharmacist whether any over-the-counter symptom relief is appropriate for you.",
            "Ask about contraindications, interactions, allergies, age limits, and safe use before taking medicine.",
            "Do not start prescription medicine or antibiotics without a licensed clinician.",
        ],
        "monitoring": [
            "Monitor severity, temperature if relevant, hydration, breathing, and whether symptoms are improving or worsening.",
            "Record new symptoms, timing, and anything that makes symptoms better or worse.",
        ],
        "visit_preparation": [
            "Bring a short timeline of symptoms and follow-up answers.",
            "List current medicines, allergies, medical conditions, and recent travel or exposures if relevant.",
            "Prepare questions you want to ask the clinician.",
        ],
        "avoid": [
            "Do not ignore severe, sudden, or rapidly worsening symptoms.",
            "Do not mix medicines or exceed label instructions.",
            "Do not use someone else's prescription medicine.",
        ],
        "medication_reference": medication_reference,
        "care_plan_table": care_plan_table,
        "safety_note": safety_note,
        "medication_boundary": MEDICATION_BOUNDARY_TEXT,
        "mode": "deterministic_safety_fallback",
    }


def build_fallback_medication_reference(primary: str, urgent: bool) -> list[dict[str, str]]:
    if urgent:
        return [
            {
                "option": "Emergency care first",
                "purpose": "Safety assessment before symptom relief choices",
                "suitability": "Urgent symptoms should be assessed by local emergency services or urgent care.",
                "dose_boundary": DOSE_BOUNDARY_TEXT,
                "cautions": "Do not delay urgent care while looking for medicine suggestions online.",
            }
        ]
    rows = [
        {
            "option": "OTC symptom relief to discuss",
            "purpose": "Short-term relief for discomfort while monitoring symptoms",
            "suitability": "Depends on age, pregnancy status, allergies, stomach/kidney/liver history, and current medicines.",
            "dose_boundary": DOSE_BOUNDARY_TEXT,
            "cautions": "Read the Drug Facts label and ask a pharmacist if you are unsure.",
        }
    ]
    if any(keyword in primary for keyword in ["headache", "fever", "pain"]):
        rows.append(
            {
                "option": "Pain or fever reliever category",
                "purpose": "May be relevant for headache, fever, or body aches",
                "suitability": "Discuss whether acetaminophen-type or NSAID-type options are safe for your situation.",
                "dose_boundary": DOSE_BOUNDARY_TEXT,
                "cautions": "Avoid mixing products with overlapping active ingredients.",
            }
        )
    if any(keyword in primary for keyword in ["cough", "sore throat", "cold"]):
        rows.append(
            {
                "option": "Cough or throat symptom category",
                "purpose": "May be relevant for cough, throat irritation, or congestion",
                "suitability": "Ask a pharmacist which product type matches dry cough, productive cough, or throat irritation.",
                "dose_boundary": DOSE_BOUNDARY_TEXT,
                "cautions": "Some products can interact with blood pressure, thyroid, diabetes, or mood medicines.",
            }
        )
    if any(keyword in primary for keyword in ["stomach", "abdominal", "nausea", "diarrhea"]):
        rows.append(
            {
                "option": "Digestive symptom category",
                "purpose": "May be relevant for nausea, stomach discomfort, or diarrhea support",
                "suitability": "Ask whether oral rehydration or an OTC digestive symptom product is appropriate.",
                "dose_boundary": DOSE_BOUNDARY_TEXT,
                "cautions": "Seek care for severe pain, blood, dehydration, persistent vomiting, or worsening symptoms.",
            }
        )
    return rows[:4]


def build_fallback_care_plan_table(primary: str, urgent: bool) -> list[dict[str, str]]:
    if urgent:
        return [
            {
                "priority": "Immediate",
                "action": "Contact local emergency services or go to urgent care.",
                "why": "Safety rules detected symptoms that may need time-sensitive assessment.",
                "when_to_seek_help": "Now, especially if symptoms are severe, sudden, or worsening.",
            }
        ]
    rows = [
        {
            "priority": "Now",
            "action": "Rest, avoid triggers, and write down symptom timing, severity, and related signs.",
            "why": "A clear timeline helps the AI summary and a clinician review the situation.",
            "when_to_seek_help": "Seek help sooner if symptoms worsen or feel unusual for you.",
        },
        {
            "priority": "Medication check",
            "action": "Review possible OTC categories with a pharmacist or clinician before using medicine.",
            "why": "Allergies, current medicines, chronic conditions, and age can change what is safe.",
            "when_to_seek_help": "Ask promptly if you are pregnant, elderly, a child, or have major chronic disease.",
        },
        {
            "priority": "Follow-up",
            "action": "Book routine care if symptoms persist, recur, or interfere with normal activities.",
            "why": "Persistent symptoms may need professional examination or tests.",
            "when_to_seek_help": "Use urgent care if red-flag symptoms appear.",
        },
    ]
    if any(keyword in primary for keyword in ["cough", "fever", "sore throat"]):
        rows.insert(
            1,
            {
                "priority": "Monitor",
                "action": "Track temperature, breathing, hydration, and symptom trend.",
                "why": "Respiratory symptoms can change quickly and need escalation if breathing becomes difficult.",
                "when_to_seek_help": "Seek urgent help for trouble breathing, blue lips, confusion, or severe weakness.",
            },
        )
    return rows[:5]


def build_live_ai_error(feature: str, message: str | None = None) -> dict[str, Any]:
    last_error = current_app.config.get("AI_LAST_ERROR")
    friendly_message = message or "This feature requires a working APIFree model call. Set APIFREE_API_KEY and restart Flask."
    if last_error and "concurrency" in str(last_error).lower():
        friendly_message = (
            "APIFree is busy because this account allows very low concurrency. "
            "Please wait about 10 seconds, then try this action again."
        )
    return {
        "error": "live_ai_required",
        "feature": feature,
        "message": friendly_message,
        "ai_configured": bool(current_app.config.get("AI_API_KEY")),
        "ai_provider": current_app.config.get("AI_PROVIDER"),
        "ai_model": current_app.config.get("AI_MODEL"),
        "ai_base_url": current_app.config.get("AI_BASE_URL"),
        "ai_last_error": current_app.config.get("AI_LAST_ERROR"),
    }


def call_model_json(
    prompt: str,
    system_prompt: str | None = None,
    required: bool = False,
) -> dict[str, Any]:
    api_key = current_app.config.get("AI_API_KEY")
    if not api_key:
        current_app.config["AI_LAST_ERROR"] = "missing_apifree_api_key"
        if required:
            raise LiveAIRequiredError("APIFree API key is not configured. Set APIFREE_API_KEY and restart Flask.")
        return {}

    base_payload = {
        "model": current_app.config["AI_MODEL"],
        "messages": [
            {
                "role": "system",
                "content": system_prompt or (
                    "You support a non-diagnostic symptom intake workflow. "
                    "Return valid JSON only. Never provide diagnosis, prescriptions, or certainty claims."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
        "top_p": 1,
        "max_tokens": 8192,
        "stream": False,
    }
    endpoint = f"{current_app.config['AI_BASE_URL'].rstrip('/')}/chat/completions"
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payloads = [
        {**base_payload, "response_format": {"type": "json_object"}},
        base_payload,
    ]
    for payload in payloads:
        for attempt in range(4):
            try:
                with APIFREE_REQUEST_LOCK:
                    response = post_without_system_proxy(
                        endpoint,
                        headers=headers,
                        json=payload,
                        timeout=current_app.config["AI_TIMEOUT_SECONDS"],
                    )
                response.raise_for_status()
                response_payload = response.json()
                provider_error = extract_provider_error(response_payload)
                if provider_error:
                    current_app.config["AI_LAST_ERROR"] = provider_error
                    if is_concurrency_error(provider_error) and attempt < 3:
                        time.sleep(3 + attempt * 3)
                        continue
                    break
                content = response_payload["choices"][0]["message"]["content"]
                parsed = parse_json_from_model_content(content)
                if parsed:
                    current_app.config["AI_LAST_ERROR"] = None
                    return parsed
                current_app.config["AI_LAST_ERROR"] = "model_response_was_not_valid_json"
                break
            except requests.HTTPError as error:
                status_code = error.response.status_code if error.response is not None else "unknown"
                current_app.config["AI_LAST_ERROR"] = f"http_error_{status_code}"
                if status_code in {429, 503} and attempt < 3:
                    time.sleep(3 + attempt * 3)
                    continue
                break
            except requests.RequestException as error:
                current_app.config["AI_LAST_ERROR"] = error.__class__.__name__
                if attempt < 2:
                    time.sleep(2 + attempt * 2)
                    continue
                break
            except (KeyError, IndexError, TypeError, ValueError, json.JSONDecodeError) as error:
                current_app.config["AI_LAST_ERROR"] = error.__class__.__name__
                break
    if required:
        raise LiveAIRequiredError(
            f"APIFree did not return usable JSON. Last error: {current_app.config.get('AI_LAST_ERROR') or 'unknown'}."
        )
    return {}


def post_without_system_proxy(url: str, **kwargs: Any) -> requests.Response:
    session = requests.Session()
    session.trust_env = False
    try:
        return session.post(url, **kwargs)
    finally:
        session.close()


def get_without_system_proxy(url: str, **kwargs: Any) -> requests.Response:
    session = requests.Session()
    session.trust_env = False
    try:
        return session.get(url, **kwargs)
    finally:
        session.close()


def is_concurrency_error(message: str) -> bool:
    lowered = message.lower()
    return "concurrency" in lowered or "rate limit" in lowered or "too many" in lowered


def extract_provider_error(payload: Any) -> str | None:
    if not isinstance(payload, dict):
        return None
    error = payload.get("error")
    if isinstance(error, dict):
        message = error.get("message") or error.get("code") or "unknown provider error"
        return f"provider_error: {str(message)[:160]}"
    if isinstance(error, str):
        return f"provider_error: {error[:160]}"
    if payload.get("code") and not payload.get("choices"):
        message = payload.get("message") or payload.get("code")
        return f"provider_error: {str(message)[:160]}"
    return None


def list_ai_models() -> tuple[dict[str, Any], int]:
    api_key = current_app.config.get("AI_API_KEY")
    endpoint = f"{current_app.config['AI_BASE_URL'].rstrip('/')}/models"
    try:
        response = get_without_system_proxy(
            endpoint,
            headers={"Authorization": f"Bearer {api_key}"},
            timeout=current_app.config["AI_TIMEOUT_SECONDS"],
        )
        response.raise_for_status()
        payload = response.json()
        models = normalize_model_list(payload)
        return {
            "provider": current_app.config.get("AI_PROVIDER"),
            "base_url": current_app.config.get("AI_BASE_URL"),
            "configured_model": current_app.config.get("AI_MODEL"),
            "models": models,
            "raw_shape": list(payload.keys()) if isinstance(payload, dict) else type(payload).__name__,
        }, 200
    except requests.HTTPError as error:
        status_code = error.response.status_code if error.response is not None else 502
        return {
            "error": f"http_error_{status_code}",
            "message": "The provider rejected the model-list request. Check APIFREE_API_KEY and account access.",
            "provider": current_app.config.get("AI_PROVIDER"),
            "base_url": current_app.config.get("AI_BASE_URL"),
        }, 502
    except requests.RequestException as error:
        return {
            "error": error.__class__.__name__,
            "message": "Could not reach the model-list endpoint.",
            "provider": current_app.config.get("AI_PROVIDER"),
            "base_url": current_app.config.get("AI_BASE_URL"),
        }, 502
    except (TypeError, ValueError, json.JSONDecodeError) as error:
        return {"error": error.__class__.__name__, "message": "Model-list response was not valid JSON."}, 502


def normalize_model_list(payload: Any) -> list[dict[str, str]]:
    if isinstance(payload, dict):
        raw_models = payload.get("data") or payload.get("models") or payload.get("result") or []
    elif isinstance(payload, list):
        raw_models = payload
    else:
        raw_models = []
    models: list[dict[str, str]] = []
    for item in raw_models:
        if isinstance(item, str):
            models.append({"id": item, "name": item})
        elif isinstance(item, dict):
            model_id = str(item.get("id") or item.get("model") or item.get("name") or "").strip()
            if model_id:
                models.append({"id": model_id, "name": str(item.get("name") or model_id)})
    return models[:100]


def parse_json_from_model_content(content: str) -> dict[str, Any]:
    text = str(content or "").strip()
    if not text:
        return {}
    try:
        parsed = json.loads(text)
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return {}
    try:
        parsed = json.loads(match.group(0))
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        return {}


def next_steps_for_triage(triage_level: str) -> str:
    if triage_level == "urgent":
        return "Seek urgent professional medical help now, especially if symptoms are severe, sudden, or worsening."
    if triage_level == "soon":
        return "Consider contacting a healthcare professional soon or arranging a timely clinic appointment."
    if triage_level == "routine":
        return "Consider booking a routine appointment or seeking professional advice if symptoms persist."
    return "Continue observing the symptom and seek professional advice if it worsens, persists, or concerns you."


def get_profiles() -> list[sqlite3.Row]:
    return get_db().execute(
        """
        SELECT user_profiles.*,
               (SELECT COUNT(*) FROM health_records WHERE health_records.profile_id = user_profiles.id) AS record_count
        FROM user_profiles
        ORDER BY updated_at DESC, id DESC
        """
    ).fetchall()


def get_profile(profile_id: int | None = 1) -> sqlite3.Row | None:
    db = get_db()
    profile_id = profile_id or 1
    profile = db.execute("SELECT * FROM user_profiles WHERE id = ?", (profile_id,)).fetchone()
    if profile is None and profile_id == 1:
        db.execute("INSERT INTO user_profiles (id, display_name) VALUES (1, 'Demo User')")
        db.commit()
        profile = db.execute("SELECT * FROM user_profiles WHERE id = 1").fetchone()
    return profile


def save_profile(payload: dict[str, Any], profile_id: int | None = None) -> int:
    db = get_db()
    values = (
        payload.get("display_name", "") or "New profile",
        nullable_int(payload.get("age")),
        payload.get("sex", ""),
        nullable_float(payload.get("height_cm")),
        nullable_float(payload.get("weight_kg")),
        payload.get("allergies", ""),
        payload.get("current_medications", ""),
        payload.get("chronic_conditions", ""),
        payload.get("past_history", ""),
        payload.get("family_history", ""),
        payload.get("emergency_contact", ""),
        1 if str(payload.get("consent_use_history", "")).lower() in {"1", "true", "on", "yes"} else 0,
    )
    if profile_id and get_profile(profile_id) is not None:
        db.execute(
            """
            UPDATE user_profiles
            SET display_name = ?, age = ?, sex = ?, height_cm = ?, weight_kg = ?,
                allergies = ?, current_medications = ?, chronic_conditions = ?,
                past_history = ?, family_history = ?, emergency_contact = ?,
                consent_use_history = ?, updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (*values, profile_id),
        )
        saved_id = profile_id
    else:
        cursor = db.execute(
            """
            INSERT INTO user_profiles
                (display_name, age, sex, height_cm, weight_kg, allergies, current_medications,
                 chronic_conditions, past_history, family_history, emergency_contact, consent_use_history)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        saved_id = int(cursor.lastrowid)
    db.commit()
    return saved_id


def nullable_int(value: Any) -> int | None:
    try:
        return int(value) if str(value).strip() else None
    except (TypeError, ValueError):
        return None


def nullable_float(value: Any) -> float | None:
    try:
        return float(value) if str(value).strip() else None
    except (TypeError, ValueError):
        return None


def save_health_record(payload: dict[str, Any]) -> int:
    profile_id = nullable_int(payload.get("profile_id")) or 1
    get_profile(profile_id)
    structured = payload.get("structured_content")
    if not structured and payload.get("source_text") and current_app.config.get("AI_API_KEY"):
        structured = json.dumps(structure_health_record(str(payload["source_text"])), ensure_ascii=False, indent=2)
    cursor = get_db().execute(
        """
        INSERT INTO health_records
            (profile_id, record_type, title, record_date, source_text, structured_content)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            profile_id,
            normalize_record_type(payload.get("record_type")),
            payload.get("title") or "Health record",
            payload.get("record_date") or "",
            payload.get("source_text") or "",
            structured or "{}",
        ),
    )
    get_db().commit()
    return int(cursor.lastrowid)


def get_health_record(record_id: int) -> sqlite3.Row:
    return get_db().execute("SELECT * FROM health_records WHERE id = ?", (record_id,)).fetchone()


def get_health_records(profile_id: int = 1) -> list[sqlite3.Row]:
    return get_db().execute(
        "SELECT * FROM health_records WHERE profile_id = ? ORDER BY created_at DESC, id DESC",
        (profile_id,),
    ).fetchall()


def structure_health_record(source_text: str) -> dict[str, Any]:
    prompt = (
        "Structure this user-provided checkup or health record text as JSON. "
        "Return keys: title, record_date, abnormal_findings, normal_findings, medicines_mentioned, "
        "conditions_mentioned, follow_up_questions, safety_note. "
        "Do not diagnose or prescribe. Keep uncertain fields as 'not specified'. "
        f"Record text: {source_text[:5000]}"
    )
    model_result = call_model_json(prompt, required=True)
    if model_result:
        return model_result
    lines = [line.strip() for line in source_text.splitlines() if line.strip()]
    abnormal_keywords = ("high", "low", "positive", "abnormal", "elevated", "reduced", "偏高", "偏低", "阳性", "异常")
    abnormal = [line for line in lines if any(keyword in line.lower() for keyword in abnormal_keywords)]
    return {
        "title": "Imported health record",
        "record_date": "not specified",
        "abnormal_findings": abnormal[:8] or ["not specified"],
        "normal_findings": [line for line in lines[:8] if line not in abnormal] or ["not specified"],
        "medicines_mentioned": ["not specified"],
        "conditions_mentioned": ["not specified"],
        "follow_up_questions": [
            "Ask a clinician which findings matter for your symptoms.",
            "Ask whether any result needs repeat testing or routine follow-up.",
        ],
        "safety_note": "Structured for organization only; not a diagnosis or treatment plan.",
    }


def structure_health_record(source_text: str) -> dict[str, Any]:
    prompt = (
        "Convert the user-provided checkup or health record text into one unified JSON report format. "
        "Return valid JSON only with exactly these top-level keys: report_title, patient_profile, checkup_info, "
        "vitals, lab_results, imaging_results, abnormal_findings, summary, suggestions, data_quality, disclaimer. "
        "patient_profile must include name, age, sex, allergies, current_medications, chronic_conditions. "
        "checkup_info must include checkup_date, institution, source_type. "
        "vitals must include height, weight, blood_pressure, heart_rate, bmi. "
        "Each lab_results item must include item_name, value, unit, reference_range, status, note. "
        "Each abnormal_findings item must include finding, possible_meaning, follow_up_suggestion. "
        "Do not diagnose, prescribe, or invent missing values; use 'not specified' and list uncertainty in data_quality. "
        f"Record text: {source_text[:5000]}"
    )
    model_result = call_model_json(prompt, required=True)
    return normalize_health_report(model_result, source_text)


def generate_uml_diagram(diagram_type: str, business_problem: str) -> dict[str, Any]:
    type_labels = {
        "use_case": "PlantUML use case diagram",
        "activity": "PlantUML activity diagram",
        "class": "PlantUML class diagram",
        "sequence": "PlantUML sequence diagram",
    }
    system_prompt = (
        "You are a software modelling assistant for a coursework meta-software generator. "
        "Return valid JSON only. Generate concise, syntactically valid PlantUML. "
        "Do not include markdown fences."
    )
    prompt = (
        f"Business problem: {business_problem}\n"
        f"Diagram type: {type_labels[diagram_type]}\n"
        "Return JSON with keys: diagram_type, title, plantuml, explanation. "
        "The plantuml value must start with @startuml and end with @enduml. "
        "Keep labels short and suitable for a Flask API and website project. "
        "Make the diagram specific to the submitted business problem. "
        "If the business problem is about AI symptom intake, include symptom input, "
        "safety checks, AI follow-up, structured summary, non-diagnostic guidance, "
        "profile/history consent, SQLite storage, and protected backend AI calls where appropriate. "
        "Do not invent login, token verification, payment, or unrelated authentication steps unless "
        "the business problem explicitly asks for them."
    )
    model_result = call_model_json(prompt, system_prompt=system_prompt, required=True)
    plantuml = str(model_result.get("plantuml") or "").strip()
    if not plantuml.startswith("@startuml") or not plantuml.endswith("@enduml"):
        current_app.config["AI_LAST_ERROR"] = "uml_generation_missing_valid_plantuml"
        raise LiveAIRequiredError("APIFree returned JSON, but it did not include valid PlantUML.")
    return {
        "diagram_type": diagram_type,
        "title": str(model_result.get("title") or type_labels[diagram_type]),
        "plantuml": plantuml,
        "explanation": str(model_result.get("explanation") or "Generated from the submitted business problem."),
        "render_svg_url": plantuml_render_url(plantuml, "svg"),
        "render_png_url": plantuml_render_url(plantuml, "png"),
        "ai_source": "apifree_live",
        "provider": current_app.config.get("AI_PROVIDER"),
        "model": current_app.config.get("AI_MODEL"),
    }


def plantuml_render_url(plantuml: str, output_format: str = "svg") -> str:
    encoded = plantuml_encode(plantuml)
    safe_format = "png" if output_format == "png" else "svg"
    return f"https://www.plantuml.com/plantuml/{safe_format}/{encoded}"


def plantuml_encode(plantuml: str) -> str:
    compressor = zlib.compressobj(level=9, wbits=-15)
    compressed = compressor.compress(plantuml.encode("utf-8")) + compressor.flush()
    return "".join(_plantuml_append3bytes(compressed[i : i + 3]) for i in range(0, len(compressed), 3))


def _plantuml_append3bytes(chunk: bytes) -> str:
    b1 = chunk[0]
    b2 = chunk[1] if len(chunk) > 1 else 0
    b3 = chunk[2] if len(chunk) > 2 else 0
    c1 = b1 >> 2
    c2 = ((b1 & 0x3) << 4) | (b2 >> 4)
    c3 = ((b2 & 0xF) << 2) | (b3 >> 6)
    c4 = b3 & 0x3F
    if len(chunk) == 1:
        return _plantuml_encode6bit(c1) + _plantuml_encode6bit(c2)
    if len(chunk) == 2:
        return _plantuml_encode6bit(c1) + _plantuml_encode6bit(c2) + _plantuml_encode6bit(c3)
    return (
        _plantuml_encode6bit(c1)
        + _plantuml_encode6bit(c2)
        + _plantuml_encode6bit(c3)
        + _plantuml_encode6bit(c4)
    )


def _plantuml_encode6bit(value: int) -> str:
    if value < 10:
        return chr(48 + value)
    value -= 10
    if value < 26:
        return chr(65 + value)
    value -= 26
    if value < 26:
        return chr(97 + value)
    value -= 26
    if value == 0:
        return "-"
    if value == 1:
        return "_"
    return "?"


def normalize_health_report(report: dict[str, Any], source_text: str = "") -> dict[str, Any]:
    def object_value(value: Any, fallback: dict[str, Any]) -> dict[str, Any]:
        return value if isinstance(value, dict) else fallback

    def list_value(value: Any) -> list[Any]:
        if isinstance(value, list):
            return value
        if value in (None, ""):
            return []
        return [value]

    blood_pressure_match = re.search(r"\b\d{2,3}/\d{2,3}\b", source_text)
    normalized = {
        "report_title": str(report.get("report_title") or report.get("title") or "AI Structured Health Checkup Report"),
        "patient_profile": object_value(
            report.get("patient_profile"),
            {
                "name": "not specified",
                "age": "not specified",
                "sex": "not specified",
                "allergies": "not specified",
                "current_medications": "not specified",
                "chronic_conditions": "not specified",
            },
        ),
        "checkup_info": object_value(
            report.get("checkup_info"),
            {
                "checkup_date": str(report.get("record_date") or "not specified"),
                "institution": "not specified",
                "source_type": "pasted_checkup_text",
            },
        ),
        "vitals": object_value(
            report.get("vitals"),
            {
                "height": "not specified",
                "weight": "not specified",
                "blood_pressure": blood_pressure_match.group(0) if blood_pressure_match else "not specified",
                "heart_rate": "not specified",
                "bmi": "not specified",
            },
        ),
        "lab_results": list_value(report.get("lab_results")),
        "imaging_results": list_value(report.get("imaging_results")),
        "abnormal_findings": list_value(report.get("abnormal_findings")),
        "summary": str(report.get("summary") or "Checkup text structured into a unified report format."),
        "suggestions": list_value(report.get("suggestions") or report.get("follow_up_questions")),
        "data_quality": object_value(report.get("data_quality"), {"missing_fields": [], "uncertain_items": []}),
        "disclaimer": str(
            report.get("disclaimer")
            or report.get("safety_note")
            or "This report is AI-structured for coursework demonstration only. It is not a diagnosis and does not replace a licensed clinician."
        ),
    }
    if not normalized["lab_results"]:
        normalized["lab_results"] = [
            {
                "item_name": "not specified",
                "value": "not specified",
                "unit": "not specified",
                "reference_range": "not specified",
                "status": "unknown",
                "note": "No lab results were found.",
            }
        ]
    if not normalized["abnormal_findings"]:
        normalized["abnormal_findings"] = [
            {
                "finding": "not specified",
                "possible_meaning": "No abnormal findings were extracted.",
                "follow_up_suggestion": "Review the original report with a licensed professional if unsure.",
            }
        ]
    if not normalized["suggestions"]:
        normalized["suggestions"] = ["Keep the original report and ask a clinician about unclear items."]
    return normalized


def build_model_profile_context(profile_id: int = 1, require_consent: bool = True) -> dict[str, Any]:
    profile = get_profile(profile_id) or get_profile(1)
    if not profile:
        return {"profile_context_allowed": False, "reason": "profile_not_found"}
    if require_consent and not profile["consent_use_history"]:
        return {
            "profile_context_allowed": False,
            "reason": "profile_history_consent_not_enabled",
            "profile_id": profile["id"],
        }
    records = get_health_records(profile["id"])[:8]
    categories: dict[str, list[dict[str, Any]]] = {}
    for record in records:
        category = normalize_record_type(record["record_type"])
        categories.setdefault(category, []).append(
            {
                "title": record["title"],
                "record_date": record["record_date"],
                "record_type": category,
                "structured_content": record["structured_content"][:1200] if record["structured_content"] else "",
            }
        )
    return {
        "profile_context_allowed": True,
        "profile": {
            "age": profile["age"],
            "sex": profile["sex"],
            "allergies": profile["allergies"],
            "current_medications": profile["current_medications"],
            "chronic_conditions": profile["chronic_conditions"],
            "past_history": profile["past_history"],
        },
        "record_categories": {category: len(items) for category, items in categories.items()},
        "categorized_recent_records": categories,
    }


def normalize_record_type(value: Any) -> str:
    text = str(value or "checkup").strip().lower().replace(" ", "_")
    allowed = {"checkup", "lab", "imaging", "medication", "visit_note", "history", "other"}
    return text if text in allowed else "other"


def insert_followup_question(session_id: int, question_text: str) -> int:
    cursor = get_db().execute(
        "INSERT INTO followup_questions (session_id, question_text) VALUES (?, ?)",
        (session_id, question_text),
    )
    return int(cursor.lastrowid)


def save_followup_answer(session_id: int, question_id: int, answer_text: str) -> None:
    get_db().execute(
        "UPDATE followup_questions SET answer_text = ? WHERE id = ? AND session_id = ?",
        (answer_text, question_id, session_id),
    )
    get_db().commit()


def get_session(session_id: int | None) -> sqlite3.Row | None:
    if session_id is None:
        return None
    return get_db().execute("SELECT * FROM user_sessions WHERE id = ?", (session_id,)).fetchone()


def get_symptom_input(session_id: int | None) -> sqlite3.Row | None:
    if session_id is None:
        return None
    return get_db().execute("SELECT * FROM symptom_inputs WHERE session_id = ?", (session_id,)).fetchone()


def get_questions(session_id: int) -> list[sqlite3.Row]:
    return get_db().execute(
        "SELECT * FROM followup_questions WHERE session_id = ? ORDER BY id",
        (session_id,),
    ).fetchall()


def get_latest_summary(session_id: int) -> sqlite3.Row | None:
    return get_db().execute(
        "SELECT * FROM symptom_summaries WHERE session_id = ? ORDER BY created_at DESC, id DESC LIMIT 1",
        (session_id,),
    ).fetchone()


def get_summary(summary_id: int) -> sqlite3.Row:
    return get_db().execute("SELECT * FROM symptom_summaries WHERE id = ?", (summary_id,)).fetchone()


app = create_app()


if __name__ == "__main__":
    if not DEFAULT_DATABASE.exists():
        init_db(app)
    app.run(debug=os.environ.get("FLASK_DEBUG") == "1")
